from __future__ import annotations

import asyncio
from dataclasses import dataclass, field

from .configs import PromptConfig, RuntimeConfig
from .parser.data_dict_parser import DataDictionary, load_data_dictionary
from .llm_client import LLMClient, LLMClientError, LLMRequest
from .parser.pdf_parser import is_pdf_parser_available, parse_pdf
from .utils.io_utils import (
    FailureRecord,
    ensure_directory,
    read_candidates_csv,
    write_candidates_csv,
    write_failures_csv,
    write_jsonl,
)
from .utils.progress import progress
from .validation.report_rating import CandidateReport, discover_candidate_sections, rate_reports
from .validation.result_validation import validate_generated_sample


@dataclass
class PipelineResult:
    stage: str
    output_dir: str
    candidate_count: int = 0
    failure_count: int = 0
    candidates_path: str | None = None
    failures_path: str | None = None
    notes: list[str] = field(default_factory=list)


def run_pipeline(config: RuntimeConfig) -> PipelineResult:
    if config.stage == "discovery":
        return run_discovery(config)
    if config.stage == "generate":
        return run_generation(config)
    raise ValueError(f"Unsupported stage: {config.stage}")


def run_discovery(config: RuntimeConfig) -> PipelineResult:
    ensure_directory(config.output_dir)
    data_dictionary = load_data_dictionary(config.data_dict_path)
    pdf_paths = sorted(config.report_dir.glob("*.pdf"))
    candidates, failures = rate_reports(
        pdf_paths=pdf_paths,
        top_k=config.max_samples_generation,
        data_dictionary=data_dictionary,
    )
    candidates_path = config.output_dir / "candidates.csv"
    failures_path = config.output_dir / "failures.csv"
    write_candidates_csv(candidates_path, candidates)
    write_failures_csv(failures_path, failures)
    notes: list[str] = []
    if not pdf_paths:
        notes.append("No PDF reports found under report directory.")
    if not is_pdf_parser_available():
        notes.append("PyPDF2 is not installed. Discovery exported explicit parse failures for each report.")
    if not data_dictionary.allowed_factor_fields:
        notes.append("Data dictionary parsed successfully but no usable fields were detected.")
    return PipelineResult(
        stage=config.stage,
        output_dir=str(config.output_dir),
        candidate_count=len(candidates),
        failure_count=len(failures),
        candidates_path=str(candidates_path),
        failures_path=str(failures_path),
        notes=notes,
    )


def run_generation(config: RuntimeConfig) -> PipelineResult:
    ensure_directory(config.output_dir)
    data_dictionary = load_data_dictionary(config.data_dict_path)
    candidates_path = config.output_dir / "candidates.csv"
    samples_path = config.output_dir / "samples.jsonl"
    failures_path = config.output_dir / "failures.csv"
    candidate_rows = read_candidates_csv(candidates_path)
    if not candidate_rows:
        failure = FailureRecord(
            stage="generate",
            report_title="",
            reason_type="OTHER",
            reason="No candidate reports found. Run discovery first.",
        )
        write_failures_csv(failures_path, [failure])
        write_jsonl(samples_path, [])
        return PipelineResult(
            stage=config.stage,
            output_dir=str(config.output_dir),
            failure_count=1,
            failures_path=str(failures_path),
            notes=["Generation requires candidates.csv generated by the discovery stage."],
        )

    samples, failures = asyncio.run(
        _run_generation_async(
            candidate_rows=candidate_rows,
            config=config,
            data_dictionary=data_dictionary,
        )
    )
    write_failures_csv(failures_path, failures)
    write_jsonl(samples_path, samples)
    return PipelineResult(
        stage=config.stage,
        output_dir=str(config.output_dir),
        candidate_count=len(samples),
        failure_count=len(failures),
        candidates_path=str(candidates_path),
        failures_path=str(failures_path),
        notes=[],
    )


async def _run_generation_async(
    *,
    candidate_rows: list[dict[str, str]],
    config: RuntimeConfig,
    data_dictionary: DataDictionary,
) -> tuple[list[dict], list[FailureRecord]]:
    client = LLMClient(config.llm)
    failures: list[FailureRecord] = []
    samples: list[dict] = []
    limited_rows = candidate_rows[: config.max_samples_generation]
    for row in progress(limited_rows, total=len(limited_rows), desc="Generation"):
        if len(samples) >= config.max_samples_generation:
            break
        report_title = row.get("report_title", "")
        report_path = row.get("report_path", "")
        try:
            parsed = parse_pdf(report_path)
            context_payload = _build_context_payload(
                parsed_full_text=parsed.full_text,
                context_mode=config.context_mode,
            )
            if context_payload is None:
                failures.append(
                    FailureRecord(
                        stage="generate",
                        report_title=report_title,
                        reason_type="NO_FACTOR_FOUND",
                        reason="No high-confidence candidate section was found for generation.",
                    )
                )
                continue
            request = _build_generation_request(
                report_title=report_title,
                report_date=row.get("report_date") or None,
                broker=row.get("broker") or None,
                context_mode=config.context_mode,
                context_payload=context_payload,
                data_dictionary=data_dictionary,
                max_factors_per_report=config.max_factors_per_report,
                prompts=config.prompts,
            )
            response_payload = await client.generate_json(request, max_qps=config.max_qps)
        except LLMClientError as exc:
            failures.append(
                FailureRecord(
                    stage="generate",
                    report_title=report_title,
                    reason_type="OTHER",
                    reason=str(exc),
                )
            )
            continue
        except Exception as exc:  # noqa: BLE001
            failures.append(
                FailureRecord(
                    stage="generate",
                    report_title=report_title,
                    reason_type="OTHER",
                    reason=str(exc),
                )
            )
            continue

        raw_samples = response_payload.get("samples")
        if not isinstance(raw_samples, list):
            failures.append(
                FailureRecord(
                    stage="generate",
                    report_title=report_title,
                    reason_type="INVALID_JSON",
                    reason="LLM payload must contain a samples list.",
                )
            )
            continue

        deduplicated = 0
        for raw_sample in raw_samples:
            if len(samples) >= config.max_samples_generation:
                break
            if deduplicated >= config.max_factors_per_report:
                break
            if not isinstance(raw_sample, dict):
                failures.append(
                    FailureRecord(
                        stage="generate",
                        report_title=report_title,
                        reason_type="INVALID_JSON",
                        reason="Each generated sample must be a JSON object.",
                    )
                )
                continue
            errors = validate_generated_sample(raw_sample, data_dictionary)
            if errors:
                failures.append(
                    FailureRecord(
                        stage="generate",
                        report_title=report_title,
                        reason_type="INVALID_CODE",
                        reason="; ".join(errors),
                    )
                )
                continue
            deduplicated += 1
            samples.append(
                _normalize_sample(
                    raw_sample=raw_sample,
                    report_title=report_title,
                    report_date=row.get("report_date") or None,
                    broker=row.get("broker") or None,
                    sample_index=deduplicated,
                )
            )
    return samples, failures


def _build_generation_request(
    *,
    report_title: str,
    report_date: str | None,
    broker: str | None,
    context_mode: str,
    context_payload: str,
    data_dictionary: DataDictionary,
    max_factors_per_report: int,
    prompts: PromptConfig,
) -> LLMRequest:
    allowed_fields = ", ".join(sorted(data_dictionary.allowed_factor_fields))
    system_prompt = prompts.generation_system_prompt
    user_prompt = prompts.generation_user_prompt_template.format(
        report_title=report_title,
        report_date=report_date,
        broker=broker,
        context_mode=context_mode,
        max_factors_per_report=max_factors_per_report,
        allowed_fields=allowed_fields,
        context_payload=context_payload,
    )
    return LLMRequest(system_prompt=system_prompt, user_prompt=user_prompt)


def _normalize_sample(
    *,
    raw_sample: dict,
    report_title: str,
    report_date: str | None,
    broker: str | None,
    sample_index: int,
) -> dict:
    sample_id = f"{_slugify(report_title)}_{sample_index:02d}"
    return {
        "sample_id": sample_id,
        "report_title": report_title,
        "report_date": report_date,
        "broker": broker,
        "inspiration": raw_sample["inspiration"].strip(),
        "reasoning": raw_sample["reasoning"].strip(),
        "factor_python": raw_sample["factor_python"].strip(),
        "required_inputs": raw_sample["required_inputs"],
        "inavailable_inputs": raw_sample["inavailable_inputs"],
    }


def _slugify(text: str) -> str:
    return "".join(ch if ch.isalnum() else "_" for ch in text).strip("_").lower()[:80]


def _build_context_payload(*, parsed_full_text: str, context_mode: str) -> str | None:
    if context_mode == "full_text":
        return parsed_full_text
    if context_mode == "section":
        candidate_sections = discover_candidate_sections(parsed_full_text)
        if not candidate_sections:
            return None
        return "\n\n".join(
            f"[候选片段 {index}]\n{section}"
            for index, section in enumerate(candidate_sections, start=1)
        )
    raise ValueError(f"Unsupported context_mode: {context_mode}")
